apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_HOST: bG9jYWxob3N0
  DB_PORT: NTQzMg==
  POSTGRES_DB: ZW1wbG95ZWVzX2Ri
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
